#!/bin/bash
log=/var/log/exim_spamlog
date=$(date '+%Y-%m-%d %H:%M:%S')

# Interval in seconds, must not exceed 60 (seconds)
interval="15"
counter="0"

# Count all queue
count_queue_all () {
    exim -bpc
    return 0
}

# Count all queue frozen
frozen () {
        count=$(exim -bp|grep frozen|awk {'print $3'}|wc -l)
        if [ $count -ne 0 ]; then
                echo -e "$date $(hostname -a) Remove frozen with amount frozen. Amount: $count" >> /var/log/exim_spamlog
                exim -bpr | grep frozen | awk {'print $3'} | xargs exim -Mrm > /dev/null 2>&1
        fi
}
# Detect sender over 50 and less than 300 messages in a short time
count_sender () {
    exim -bpr | grep "<*@*>" | awk {'print $4'} |grep -v "<>" | cut -d "<" -f 2 | cut -d ">" -f 1 | sort | uniq -c | sort -n| awk {'print $2'}| while read sender
    do
        count=$(exiqgrep -f $sender |grep "<"|wc -l)
        count_old=$(exiqgrep -f $sender -o 1800|grep "<"|wc -l)
        domain="$(echo "${sender}" | cut -d'@' -f2)"
        account="$(cat /etc/userdomains | grep "${domain}" | cut -d' ' -f2)"
        local_domain=`grep -E ^$domain /etc/localdomains | awk '{print $1}'`
        suspend_outgoing=`grep -E ^$sender /etc/outgoing_mail_suspended_users | awk '{print $1}'`
        if [ $count -ge 50 ] && [ $count -lt 100 ] && [ -n $local_domain ] && [ -z $suspend_outgoing ]; then
                echo -e "$date $(hostname -a) $sender is attempting to send over 50 messages. Amount: $count" >> /var/log/exim_spamlog
        elif [ $count -ge 50 ] && [ $count -lt 100 ] && [ -n $local_domain ] && [ -n $suspend_outgoing ]; then
                echo -e "$date $(hostname -a) $sender is attempting to send over 50 messages. Amount: $count" >> /var/log/exim_spamlog
        elif [ $count -ge 100 ] && [ $count -lt 300 ] && [ -n $local_domain ] && [ -z $suspend_outgoing ]; then
                echo -e "$date $(hostname -a) $sender is attempting to send over 100 messages. Amount: $count" >> /var/log/exim_spamlog
        elif [ $count -ge 100 ] && [ $count -lt 300 ] && [ -n $local_domain ] && [ -n $suspend_outgoing ]; then
                echo -e "$date $(hostname -a) $sender is attempting to send over 100 messages. Amount: $count" >> /var/log/exim_spamlog
        fi
    done
}
# Detect sender in 5 minutes send over 300 messages
count_sender_5m () {
    exim -bpr | grep "<*@*>" | awk {'print $4'} |grep -v "<>" | cut -d "<" -f 2 | cut -d ">" -f 1 | sort | uniq -c | sort -n| awk {'print $2'}| while read sender
    do
        count=$(exiqgrep -f $sender -o 300|grep "<"|wc -l)
        domain="$(echo "${sender}" | cut -d'@' -f2)"
        account="$(cat /etc/userdomains | grep "${domain}" | cut -d' ' -f2)"
        local_domain=`grep -E ^$domain /etc/localdomains | awk '{print $1}'`
        suspend_outgoing=`grep -E ^$sender /etc/outgoing_mail_suspended_users | awk '{print $1}'`
        if [ $count -ge 300 ] && [ $count -lt 500 ] && [ -n $local_domain ] && [ -z $suspend_outgoing ]; then
                uapi --user=$account Email suspend_outgoing email=$sender
                echo -e "$date $(hostname -a) $sender is attempting to send over 300 messages. Amount: $count" >> /var/log/exim_spamlog
        elif [ $count -ge 300 ] && [ $count -lt 500 ] && [ -n $local_domain ] && [ -n $suspend_outgoing ]; then
                uapi --user=$account Email suspend_login email=$sender
                exim -bp | grep $sender | awk {'print $3'} | xargs exim -Mrm
                echo -e "$date $(hostname -a) $sender is attempting to send over 300 messages. Amount: $count" >> /var/log/exim_spamlog
        fi
    done
}
# Detect sender in 15 minutes send over 500 messages
count_sender_15m () {
    exim -bpr | grep "<*@*>" | awk {'print $4'} |grep -v "<>" | cut -d "<" -f 2 | cut -d ">" -f 1 | sort | uniq -c | sort -n| awk {'print $2'}| while read sender
    do
        count=$(exiqgrep -f $sender -o 600|grep "<"|wc -l)
        domain="$(echo "${sender}" | cut -d'@' -f2)"
        account="$(cat /etc/userdomains | grep "${domain}" | cut -d' ' -f2)"
        local_domain=`grep -E ^$domain /etc/localdomains | awk '{print $1}'`
        suspend_outgoing=`grep -E ^$sender /etc/outgoing_mail_suspended_users | awk '{print $1}'`
        if [ $count -ge 500 ] && [ -n $local_domain ] && [ -z $suspend_outgoing ]; then
                uapi --user=$account Email suspend_outgoing email=$sender
                uapi --user=$account Email suspend_login email=$sender
                exim -bp | grep $sender | awk {'print $3'} | xargs exim -Mrm
                echo "The address \"$sender\" on $(hostname) is attempting to send over 500 messages within 15 minutes. Amount: $count" | mail -s "Spam Alert: $sender Spam On $(hostname)" 87849bc1.axys.asia@apac.teams.ms
                echo -e "$date $(hostname -a) $sender is attempting to send over 500 messages. Amount: $count" >> /var/log/exim_spamlog
        elif [ $count -ge 500 ] && [ -n $local_domain ] && [ -n $suspend_outgoing ]; then
                uapi --user=$account Email suspend_login email=$sender
                exim -bp | grep $sender | awk {'print $3'} | xargs exim -Mrm
                echo "The address \"$sender\" on $(hostname) is attempting to send over 500 messages within 15 minutes. Amount: $count" | mail -s "Spam Alert: $sender Spam On $(hostname)" 87849bc1.axys.asia@apac.teams.ms
                echo -e "$date $(hostname -a) $sender is attempting to send over 500 messages. Amount: $count" >> /var/log/exim_spamlog
        fi
    done
}

while [ $counter -lt 60 ]; do
    if [ $(count_queue_all) -lt 300 ]; then
        count_sender
        frozen
    elif [ $(count_queue_all) -lt 500 ]; then
        count_sender_5m
        frozen
    else
        count_sender_15m
        frozen
        exit 1
    fi

    sleep $interval
    counter=$[$counter+$interval]
done
exit 0
