#!/bin/bash
CPU=`nproc`
CPU=$(vmstat 1 2 | tail -1 | awk '{printf("%d %d %d %d %d",$13,$14,$15,$16,$17)}')

if [ -f "/etc/redhat-release" ]; then
        RAM=`free | awk 'NR==2 {printf("%d %d %d %d",$2,$4,$6,$7)}'`
        RAM_SWAP=`free | grep "^Swap:" | awk '{printf("%d %d %d",$2,$3,$4)}'`
elif [ -f "/etc/lsb-release" ]; then
        RAM=`free -w | awk 'NR==2 {printf("%d %d %d %d",$2,$4,$6,$7)}'`
        RAM-SWAP=`free | grep "^Swap:" | awk '{printf("%d %d %d",$2,$3,$4)}'`
else
        echo "Not supported distribution."
fi

DISK=`df /home | awk 'NR==2 {printf("%d %d %d %d",$2,$3,$4,$5)}'`
DOMAIN=$(find /var/cpanel/users ! -name "system" -type f -print | wc -l)
DOMAIN_SUSPENDED=$(find /var/cpanel/suspended/ -type f -print | wc -l)
EMAIL=$(sed "s|:||g" /etc/userdomains | awk '!/^\* nobody/{print $1, $2 | "sort | uniq" }' | awk '{print "cat /home/"$2"/etc/"$1"/passwd"}' | sh 2>/dev/null | wc -l)
QUEUE=$(exim -bpc)
SESSION_SMTP=$(netstat -anpl | grep ':25\|:465' | wc -l)
SESSION_IMAP=$(netstat -anpl | grep ':143\|:993' | wc -l)
SESSION_POP=$(netstat -anpl | grep ':110\|:990' | wc -l)

# Retrieve each element for CPU
CPU_User=`echo $CPU | awk '{print $1}'`
CPU_System=`echo $CPU | awk '{print $2}'`
CPU_Idle=`echo $CPU | awk '{print $3}'`
CPU_IOWait=`echo $CPU | awk '{print $4}'`
CPU_Steal=`echo $CPU | awk '{print $5}'`

# Retrieve each element for RAM
RAM_Total=`echo $RAM | awk '{print $1}'`
RAM_Free=`echo $RAM | awk '{print $2}'`
RAM_Buff=`echo $RAM | awk '{print $3}'`
RAM_Cached=`echo $RAM | awk '{print $4}'`

# Retrieve each element for DISK
DISK_Total=`echo $DISK | awk '{print $1}'`
DISK_Used=`echo $DISK | awk '{print $2}'`
DISK_Avail=`echo $DISK | awk '{print $3}'`
DISK_UsedPercent=`echo $DISK | awk '{print $4}'`

# Create JSON string
echo "$CPU_User - $CPU_System - $CPU_Idle - $CPU_IOWait - $CPU_Steal - $RAM_Total - $RAM_Free - $RAM_Buff - $RAM_Cached - $DISK_Total - $DISK_Used - $DISK_Avail - $DISK_UsedPercent - $DOMAIN - $DOMAIN_SUSPENDED - $EMAIL - $QUEUE - $SESSION_SMTP - $SESSION_IMAP - $SESSION_POP"| \
awk \
'{printf("{\
\"CPU_USER\":%d ,\
\"CPU_SYSTEM\":%d ,\
\"CPU_IDLE\":%d ,\
\"CPU_IOWAIT\":%d ,\
\"CPU_STEAL\":%d ,\
\"RAM_TOTAL\":%d ,\
\"RAM_FREE\":%d ,\
\"RAM_BUFF\":%d ,\
\"RAM_CACHED\":%d} ,\
\"DISK_TOTAL\":%d ,\
\"DISK_USED\":%d ,\
\"DISK_AVAIL\":%d ,\
\"DISK_USED%\":%d ,\
\"DOMAIN_TOTAL\":%d ,\
\"DOMAIN_SUSPENDED\":%d ,\
\"EMAIL\":%d ,\
\"QUEUE\":%d ,\
\"SESSION_SMTP\":%d ,\
\"SESSION_IMAP\":%d ,\
\"SESSION_POP\":%d}" ,\
$1,$3,$5,$7,$9,$11,$13,$15,$17,$19,$21,$23,$25,$27,$29,$31,$33,$35,$37,$39)}'
