#!/bin/bash
CORE=`nproc`
CPU=$(vmstat 1 2 | tail -1 | awk '{printf("%d %d %d %d %d",$13,$14,$15,$16,$17)}')

# Retrieve each element for CPU
CPU_User=`echo $CPU | awk '{print $1}'`
CPU_System=`echo $CPU | awk '{print $2}'`
CPU_Idle=`echo $CPU | awk '{print $3}'`
CPU_IOWait=`echo $CPU | awk '{print $4}'`
CPU_Steal=`echo $CPU | awk '{print $5}'`

# Create JSON string for CPU
echo "$CORE - $CPU_User - $CPU_System - $CPU_Idle - $CPU_IOWait - $CPU_Steal"| \
awk \
'{printf("{\
\"CORE\":%d ,\
\"CPU_USER\":%d ,\
\"CPU_SYSTEM\":%d ,\
\"CPU_IDLE\":%d ,\
\"CPU_IOWAIT\":%d ,\
\"CPU_STEAL\":%d}" ,\
$1,$3,$5,$7,$9,$11)}'
