#!/bin/bash
# Prepare the environment
IPv4_WAN_OLD="103.15.48.214"
IPv4_LAN_OLD="192.168.48.214"
IPv4_WAN_NEW=$(ip -4 addr show dev eth0 | sed -ne 's|^.* inet \([^/]*\)/.* scope global.*$|\1|p')

## Change the server's Network
function Network() {
    echo ""
    echo "Tell me the local IP address of the server."
    echo ""

    read -rp "IPv4 LAN: " -e IPv4_LAN_NEW
    MacAddr_LAN_OLD="00:1c:42:09:b3:34"
    MacAddr_LAN_NEW=$(ip link show eth1 | grep "link/ether" | awk '{print $2}')
    ### Modify IPv4 LAN
    sed -i "s/$IPv4_LAN_OLD/$IPv4_LAN_NEW/g" /etc/sysconfig/network-scripts/ifcfg-eth1
    ### Modify MACADDR LAN
    sed -i "s/$MacAddr_LAN_OLD/$MacAddr_LAN_NEW/g" /etc/sysconfig/network-scripts/ifcfg-eth1
    ### UP IPv4 LAN
    ifup eth1
}

## Change the server's IP
function IP() {
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /etc/wwwacct.conf
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /var/cpanel/mainip
    /usr/local/cpanel/bin/setsiteip -u salehost $IPv4_WAN_NEW
}

## Change the server’s Hostname
function Hostname() {
    echo ""
    echo "Tell me the Hostname of the server."
    echo ""

    read -rp "HOSTNAME: " -e HOSTNAME
    /usr/local/cpanel/bin/set_hostname $HOSTNAME
    sed -i "s/proxx.emailserver.vn/$HOSTNAME/g" /etc/wwwacct.conf
    sed -i "s/proxx.emailserver.vn/$HOSTNAME/g" /etc/my.cnf
    systemctl restart mysql
    sed -i "s/proxx.emailserver.vn/$HOSTNAME/g" /var/cpanel/cpanel.config
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /var/cpanel/userdata/nobody/"$HOSTNAME"
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /var/cpanel/userdata/nobody/"$HOSTNAME".cache
    rm -rf /var/lib/mysql/proxx.emailserver.vn.err
    rm -rf proxx.emailserver.vn-103.15.48.214.txt
}

## Change the server’s DNS
function DNS() {
    whmapi1 --output=jsonpretty killdns domain='proxx.emailserver.vn'
    whmapi1 resetzone domain='salehost.matbao.net'
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /var/named/"$HOSTNAME".db
    ### Modify file hosts
    Alias_Hostname=$(hostname -a)
    sed -i "s/$IPv4_WAN_OLD/$IPv4_WAN_NEW/g" /etc/hosts
    sed -i "s/proxx.emailserver.vn/$HOSTNAME/g" /etc/hosts
    sed -i "s/proxx/$Alias_Hostname/g" /etc/hosts
}

## Change the server's Elastic
function Elastic() {
    IPv4_LAN_NEW=$(ip -4 addr show dev eth1 | sed -ne 's|^.* inet \([^/]*\)/.* scope global.*$|\1|p')
    Alias_Hostname=$(hostname -a)
    sed -i "s/$IPv4_LAN_OLD/$IPv4_LAN_NEW/g" /etc/logstash/conf.d/cp/10_input.conf
    sed -i "s/$IPv4_LAN_OLD/$IPv4_LAN_NEW/g" /etc/logstash/logstash.yml
    sed -i "s/proxx/$Alias_Hostname/g" /etc/logstash/logstash.yml
    sed -i "s/$IPv4_LAN_OLD/$IPv4_LAN_NEW/g" /etc/filebeat/filebeat.yml
}

## Change the server's Monitor
function Monitor() {
    Alias_XX=$(hostname -a |sed 's\pro\\g')
    sed -i "s/XX/$Alias_XX/g" /etc/zabbix/zabbix_agentd.conf
}
Network
IP
Hostname
DNS
Elastic
Monitor