#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
res1=$(date +%s.%N)
me=`basename "$0"`
###########   >_   #####################################################################

# Set verbose to null
verbose=""

# Print the help text
helptext () {
    tput bold
    tput setaf 2
    echo "[cPanel]"
    echo "USAGE: $0 [Options] [Domain] [Server]"
    echo "Options:"
    echo "  -h, --help  display this help and exit"
    echo "  -all,       run on all backup, restore account and rsync data"
    echo "  -s, --sync   data sync specify account"
    echo "."
    echo "."
    echo "."
        tput bold
        tput setaf 1
        echo "- Only run 1 time!"
    tput sgr0
    exit 0
}

all () {
       domain=$1
       server=$2
       account=`grep -E ^$domain /etc/userdomains | sed 's/://g' | awk '{print $2}'`
       # Check Domain
       if [ -z $account ]; then
       echo -e "$domain does not exists on server"
                exit 1
       else
       # Backup
       echo -n "Backup - $account "
                /scripts/pkgacct $account --backup --skiplogs "/home/$account/" > /dev/null
                scp -P1797 -oStrictHostKeyChecking=no -oCheckHostIP=no /home/$account/$account.tar.gz $server:/home/ > /dev/null
       echo "- ${green}Done Backup${reset}"

       sleep 5
       # Restore
       echo -n "Restore - $account "
                ssh -p1797 -oStrictHostKeyChecking=no -oCheckHostIP=no $server "/scripts/restorepkg --force /home/$account.tar.gz" > /dev/null
       echo "- ${green}Done Restore${reset}"

       sleep 5
       # Rsync
       echo -n "Rsync - $account "
                rsync -av --delete -e "ssh -p1797 -oStrictHostKeyChecking=no -oCheckHostIP=no" /home/$account/ $server:/home/$account/ > /dev/null
       echo "- ${green}Done Rsync${reset}"
       fi
}

sync () {
        domain=$1
        server=$2
        account=`grep -E ^$domain /etc/userdomains | sed 's/://g' | awk '{print $2}'`
        if [ -z $account ]; then
        echo -e "$domain does not exists on server"
                exit 1
        else
        # Rync
        echo -n "Rsync - $account "
                rsync -av --delete -e "ssh -p1797 -oStrictHostKeyChecking=no -oCheckHostIP=no" /home/$account/ $server:/home/$account/ > /dev/null
        echo "- ${green}Done Rsync${reset}"
        fi
}

# Check the domain and server parameters are passed
if [ -z "$2" ] || [ -z "$3" ] || [ -n "$4" ] ;then
    tput bold
    tput setaf 1
    echo "Invalid Option!"
    helptext
    exit 1
fi

# Main function, switches options passed to it
case "$1" in
        -h) helptext
        ;;
        --help) helptext

        case "$2" in
                --all) all "$3" "$4"
                ;;
                -a) all "$3" "$4"
                ;;
                --sync) sync "$3" "$4"
                ;;
                -s) sync "$3" "$4"
                ;;
            *)
                        tput bold
                        tput setaf 1
                        echo "Invalid Option!"
                        helptext
                        ;;
        esac
                ;;
                -all) all "$2" "$3"
                ;;
                -a) all "$2" "$3"
                ;;
                --sync) sync "$2" "$3"
                ;;
                -s) sync "$2" "$3"
                ;;
            *)
                        tput bold
                        tput setaf 1
                        echo "Invalid Option!"
                        helptext
                        ;;
esac
###########   >_   #####################################################################
res2=$(date +%s.%N)
dt=$(echo "$res2 - $res1" | bc)
dd=$(echo "$dt/86400" | bc)
dt2=$(echo "$dt-86400*$dd" | bc)
dh=$(echo "$dt2/3600" | bc)
dt3=$(echo "$dt2-3600*$dh" | bc)
dm=$(echo "$dt3/60" | bc)
ds=$(echo "$dt3-60*$dm" | bc)
echo "============================="
printf "Total runtime: %d:%02d:%02d:%02.4f\n" $dd $dh $dm $ds
enddate=$(date +%T\ %d-%m-%Y)
echo "=    $enddate    ="
echo "============================="
