#!/bin/bash
GREEN='\e[32m'
STD='\e[39m'
# Use domain
if [ -z "$1" ]; then
    echo Usage: $0 {domain}
    exit 1
fi

# Check domain exist
echo "Preparing to check domain $1, please wait..."
sleep 3
i=`grep -E ^$1 /etc/userdomains | sed 's/://g' | awk '{print $2}'`
if [ -z $i ]; then
        echo -e "--- Domain $1 does not exist ---"
        exit 1
else
        echo -e "--- Domain $1 exist ---"
fi

# Config Email Filter fo Mailbox
ls -d /home/$i/mail/$1/*/ | awk 'BEGIN {
}
{
tcmd = "test -d " $1
if(!system(tcmd)){
split($1,MyArray,"/")
print MyArray[6] "@" MyArray[5]
}
}
'|while read Email
do
        Domain="$(echo "${Email}" | cut -d'@' -f2)"
        Account="$(cat /etc/userdomains | grep "${Domain}" | cut -d' ' -f2)"
uapi --user=$Account Email delete_filter account=$Email filtername="Move Subject [SPAM] to Junk"
echo -e "${GREEN} $Email - Done ${STD}"
done
